apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    {{- include "video-converter.labels" . | nindent 4 }}
spec:
  selector:
    app: auth
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      protocol: TCP
  type: ClusterIP
