apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels: 
    app: mongodb
spec:
  selector:
    app: mongodb
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
