apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    -- Create user table
    CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    );
    
    -- Insert an initial user (example)
    INSERT INTO user (email, password) VALUES ('georgio@email.com', 'Admin123');
    -- Ensure to use hashed passwords in production
